import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        {/* Simple, clean header */}
        <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
          <div className="max-w-7xl mx-auto px-6 py-4">
            <div className="flex items-center justify-between">
              <h1 className="text-2xl font-bold">PlaceOS</h1>
              <nav className="flex gap-6 text-sm">
                <a href="/" className="text-gray-600 hover:text-gray-900">
                  Students
                </a>
                <a href="/import" className="text-gray-600 hover:text-gray-900">
                  Import
                </a>
                <a href="/stats" className="text-gray-600 hover:text-gray-900">
                  Stats
                </a>
              </nav>
            </div>
          </div>
        </header>

        {/* Main content with generous spacing */}
        <main className="max-w-7xl mx-auto px-6 py-12">{children}</main>

        {/* Simple footer */}
        <footer className="mt-24 py-12 text-center text-sm text-gray-500">
          Built by {"{your_name}"} ·{" "}
          <a href="https://github.com/..." className="underline">
            Open Source
          </a>
        </footer>
      </body>
    </html>
  );
}
